# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'libraryManagment.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
from PyQt5.QtWidgets import QMessageBox

# connect to database
my_connection=mysql.connector.connect(
        host="localhost",
        user="you'r username",
        password="you'r passwor mysql",
        database="you'r database name"
)

# creat cursor
my_cursor=my_connection.cursor()

# myTable="""CREATE TABLE Book
#     (
#         Name varchar(250) NOT NULL,
#         Author varchar(250) NOT NULL,
#         releasData  INTEGER NOT NULL,
#         Description varchar(250) NOT NULL,
#        my_Group varchar(250) NOT NULL
#     )"""

# my_cursor.execute(myTable)


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(591, 450)
        self.myTab = QtWidgets.QTabWidget(Dialog)
        self.myTab.setGeometry(QtCore.QRect(10, 0, 571, 441))
        self.myTab.setStyleSheet("background-color: rgb(208, 217, 255);")
        self.myTab.setObjectName("myTab")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.Book_List = QtWidgets.QGroupBox(self.tab_3)
        self.Book_List.setGeometry(QtCore.QRect(10, 120, 541, 281))
        self.Book_List.setStyleSheet("background-color: rgb(230, 255, 240);")
        self.Book_List.setObjectName("Book_List")
        self.myTable = QtWidgets.QTableWidget(self.Book_List)
        self.myTable.setGeometry(QtCore.QRect(20, 30, 501, 191))
        self.myTable.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.myTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.myTable.setObjectName("myTable")
        self.myTable.setColumnCount(5)
        self.myTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.myTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.myTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.myTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.myTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.myTable.setHorizontalHeaderItem(4, item)
        self.btn_show_data = QtWidgets.QPushButton(self.Book_List,clicked=lambda:self.show_data())
        self.btn_show_data.setGeometry(QtCore.QRect(220, 230, 131, 41))
        self.btn_show_data.setStyleSheet("background-color: rgb(255, 247, 134);\n"
"color: rgb(0, 0, 0);")
        self.btn_show_data.setObjectName("btn_show_data")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(60, 10, 441, 101))
        self.groupBox_2.setStyleSheet("background-color: rgb(230, 255, 240);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(80, 30, 47, 13))
        self.label_2.setObjectName("label_2")
        self.enetr_Delete = QtWidgets.QLineEdit(self.groupBox_2)
        self.enetr_Delete.setGeometry(QtCore.QRect(160, 30, 171, 20))
        self.enetr_Delete.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enetr_Delete.setObjectName("enetr_Delete")
        self.btn_Delete = QtWidgets.QPushButton(self.groupBox_2,clicked=lambda:self.delete_Book())
        self.btn_Delete.setGeometry(QtCore.QRect(190, 60, 111, 31))
        self.btn_Delete.setStyleSheet("background-color: rgb(255, 247, 134);\n"
"color: rgb(0, 0, 0);")
        self.btn_Delete.setObjectName("btn_Delete")
        self.myTab.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lb_Add_Name = QtWidgets.QLabel(self.tab)
        self.lb_Add_Name.setGeometry(QtCore.QRect(10, 120, 111, 16))
        self.lb_Add_Name.setObjectName("lb_Add_Name")
        self.lbl_Add_Author = QtWidgets.QLabel(self.tab)
        self.lbl_Add_Author.setGeometry(QtCore.QRect(10, 160, 101, 16))
        self.lbl_Add_Author.setObjectName("lbl_Add_Author")
        self.lbl_Add_Releas_Data = QtWidgets.QLabel(self.tab)
        self.lbl_Add_Releas_Data.setGeometry(QtCore.QRect(10, 200, 101, 20))
        self.lbl_Add_Releas_Data.setObjectName("lbl_Add_Releas_Data")
        self.lbl_group = QtWidgets.QLabel(self.tab)
        self.lbl_group.setGeometry(QtCore.QRect(260, 120, 81, 16))
        self.lbl_group.setObjectName("lbl_group")
        self.lbl_Description = QtWidgets.QLabel(self.tab)
        self.lbl_Description.setGeometry(QtCore.QRect(260, 160, 101, 16))
        self.lbl_Description.setObjectName("lbl_Description")
        self.enter_Add_Name = QtWidgets.QLineEdit(self.tab)
        self.enter_Add_Name.setGeometry(QtCore.QRect(110, 120, 141, 20))
        self.enter_Add_Name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enter_Add_Name.setObjectName("enter_Add_Name")
        self.enter_Add_Author = QtWidgets.QLineEdit(self.tab)
        self.enter_Add_Author.setGeometry(QtCore.QRect(110, 160, 141, 20))
        self.enter_Add_Author.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enter_Add_Author.setObjectName("enter_Add_Author")
        self.enter_Releas_Data = QtWidgets.QLineEdit(self.tab)
        self.enter_Releas_Data.setGeometry(QtCore.QRect(110, 200, 141, 20))
        self.enter_Releas_Data.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enter_Releas_Data.setObjectName("enter_Releas_Data")
        self.enter_Add_Description = QtWidgets.QLineEdit(self.tab)
        self.enter_Add_Description.setGeometry(QtCore.QRect(350, 160, 131, 61))
        self.enter_Add_Description.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enter_Add_Description.setObjectName("enter_Add_Description")
        self.check_Iranian = QtWidgets.QCheckBox(self.tab)
        self.check_Iranian.setGeometry(QtCore.QRect(350, 120, 70, 17))
        self.check_Iranian.setObjectName("check_Iranian")
        self.check_Foriegn = QtWidgets.QCheckBox(self.tab)
        self.check_Foriegn.setGeometry(QtCore.QRect(420, 120, 70, 17))
        self.check_Foriegn.setObjectName("check_Foriegn")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(80, 30, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 249, 151);")
        self.label_7.setObjectName("label_7")
        self.btn_Add_Book = QtWidgets.QPushButton(self.tab,clicked=lambda:self.add_Book())
        self.btn_Add_Book.setGeometry(QtCore.QRect(220, 280, 151, 51))
        self.btn_Add_Book.setStyleSheet("background-color: rgb(255, 247, 134);")
        self.btn_Add_Book.setObjectName("btn_Add_Book")
        self.myTab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(80, 30, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 249, 151);")
        self.label_8.setObjectName("label_8")
        self.lbl_Add_Author_2 = QtWidgets.QLabel(self.tab_2)
        self.lbl_Add_Author_2.setGeometry(QtCore.QRect(10, 200, 101, 16))
        self.lbl_Add_Author_2.setObjectName("lbl_Add_Author_2")
        self.lbl_Description_2 = QtWidgets.QLabel(self.tab_2)
        self.lbl_Description_2.setGeometry(QtCore.QRect(260, 200, 101, 16))
        self.lbl_Description_2.setObjectName("lbl_Description_2")
        self.enter_Edite_Description = QtWidgets.QLineEdit(self.tab_2)
        self.enter_Edite_Description.setGeometry(QtCore.QRect(350, 200, 131, 61))
        self.enter_Edite_Description.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enter_Edite_Description.setObjectName("enter_Edite_Description")
        self.enter_Edite_Releas_Data = QtWidgets.QLineEdit(self.tab_2)
        self.enter_Edite_Releas_Data.setGeometry(QtCore.QRect(110, 240, 141, 20))
        self.enter_Edite_Releas_Data.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enter_Edite_Releas_Data.setObjectName("enter_Edite_Releas_Data")
        self.check_Edite_Foriegn = QtWidgets.QCheckBox(self.tab_2)
        self.check_Edite_Foriegn.setGeometry(QtCore.QRect(420, 160, 70, 17))
        self.check_Edite_Foriegn.setObjectName("check_Edite_Foriegn")
        self.lb_Add_Name_2 = QtWidgets.QLabel(self.tab_2)
        self.lb_Add_Name_2.setGeometry(QtCore.QRect(10, 160, 111, 16))
        self.lb_Add_Name_2.setObjectName("lb_Add_Name_2")
        self.enter_Edite_Author = QtWidgets.QLineEdit(self.tab_2)
        self.enter_Edite_Author.setGeometry(QtCore.QRect(110, 200, 141, 20))
        self.enter_Edite_Author.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enter_Edite_Author.setObjectName("enter_Edite_Author")
        self.check_Edite_Iranian = QtWidgets.QCheckBox(self.tab_2)
        self.check_Edite_Iranian.setGeometry(QtCore.QRect(350, 160, 70, 17))
        self.check_Edite_Iranian.setObjectName("check_Edite_Iranian")
        self.enter_Edite_Name = QtWidgets.QLineEdit(self.tab_2)
        self.enter_Edite_Name.setGeometry(QtCore.QRect(110, 160, 141, 20))
        self.enter_Edite_Name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enter_Edite_Name.setObjectName("enter_Edite_Name")
        self.lbl_Add_Releas_Data_2 = QtWidgets.QLabel(self.tab_2)
        self.lbl_Add_Releas_Data_2.setGeometry(QtCore.QRect(10, 240, 101, 20))
        self.lbl_Add_Releas_Data_2.setObjectName("lbl_Add_Releas_Data_2")
        self.lbl_group_2 = QtWidgets.QLabel(self.tab_2)
        self.lbl_group_2.setGeometry(QtCore.QRect(260, 160, 81, 16))
        self.lbl_group_2.setObjectName("lbl_group_2")
        self.btn_Edite_Book = QtWidgets.QPushButton(self.tab_2,clicked=lambda:self.edite_Book())
        self.btn_Edite_Book.setGeometry(QtCore.QRect(220, 310, 151, 51))
        self.btn_Edite_Book.setStyleSheet("background-color: rgb(255, 247, 134);")
        self.btn_Edite_Book.setObjectName("btn_Edite_Book")
        self.lbl_Name_for_Edite = QtWidgets.QLabel(self.tab_2)
        self.lbl_Name_for_Edite.setGeometry(QtCore.QRect(10, 95, 141, 31))
        self.lbl_Name_for_Edite.setObjectName("lbl_Name_for_Edite")
        self.enter_Name_for_search = QtWidgets.QLineEdit(self.tab_2)
        self.enter_Name_for_search.setGeometry(QtCore.QRect(170, 99, 141, 31))
        self.enter_Name_for_search.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enter_Name_for_search.setObjectName("enter_Name_for_search")
        self.btn_Edite_Search = QtWidgets.QPushButton(self.tab_2,clicked=lambda:self.search_Book())
        self.btn_Edite_Search.setGeometry(QtCore.QRect(330, 100, 151, 31))
        self.btn_Edite_Search.setStyleSheet("background-color: rgb(255, 247, 134);")
        self.btn_Edite_Search.setObjectName("btn_Edite_Search")
        self.myTab.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.myTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def add_Book(self):
        sql="INSERT INTO Book (Name, Author,releasData,my_Group,Description) VALUES (%s,%s,%s,%s,%s)"

        check=""

        if self.check_Iranian.isChecked():
            check="Iranian"
        elif self.check_Foriegn.isChecked():
            check="Foriegn"
        elif self.check_Iranian.isChecked()==False and self.check_Foriegn.isChecked()==False:
            check_message = QMessageBox()
            check_message.setWindowTitle("message box")
            check_message.setText("you should check one Group Book")

            x = check_message.exec_()

        value=(self.enter_Add_Name.text(),self.enter_Add_Author.text(),int(self.enter_Releas_Data.text()),check,self.enter_Add_Description.text())

        my_cursor.execute(sql,value)
        my_connection.commit()

        my_connection.close()


    def show_data(self):

        # for show data we should write connection code again 
        my_connection=mysql.connector.connect(
            host="localhost",
            user="you'r username",
            password="you'r passwor mysql",
            database="you'r database name"
        )

        my_cursor=my_connection.cursor()

        # get all record
        my_cursor.execute("SELECT * FROM Book")

        # insert record into records variable
        records=my_cursor.fetchall()

        # row of myTable
        self.myTable.setRowCount(len(records))

        # len row
        row=0

        for record in records:
            self.myTable.setItem(row,0,QtWidgets.QTableWidgetItem(record[0]))
            self.myTable.setItem(row,1,QtWidgets.QTableWidgetItem(record[1]))
            self.myTable.setItem(row,2,QtWidgets.QTableWidgetItem(str(record[2])))
            self.myTable.setItem(row,3,QtWidgets.QTableWidgetItem(record[3]))
            self.myTable.setItem(row,4,QtWidgets.QTableWidgetItem(record[4]))

            row+=1

        my_connection.commit()

    def delete_Book(self):
        
        # for Delete data we should write connection code again 
        my_connection=mysql.connector.connect(
            host="localhost",
            user="you'r username",
            password="you'r passwor mysql",
            database="you'r database name"
        )

        my_cursor=my_connection.cursor()

        name_Delete=self.enetr_Delete.text()

        # Delete data
        sql="DELETE FROM Book WHERE Name=%s"
        my_cursor.execute(sql,[(name_Delete)])

        my_connection.commit()
        my_connection.close()


    def search_Book(self):
        my_connection=mysql.connector.connect(
            host="localhost",
            user="you'r username",
            password="you'r passwor mysql",
            database="you'r database name"
        )

        my_cursor=my_connection.cursor()
        try:
            sql="SELECT * FROM book WHERE Name=%s"
            value=self.enter_Name_for_search.text()

            my_cursor.execute(sql,[(value)])

            data=my_cursor.fetchone()

            self.enter_Edite_Name.setText(data[0])
            self.enter_Edite_Author.setText(data[1])
            self.enter_Edite_Releas_Data.setText(str(data[2]))      
            self.enter_Edite_Description.setText(data[3])
        except TypeError:
            info_msg = QMessageBox()
            info_msg.setWindowTitle("Information message box")
            info_msg.setText("please Enter Name Book in Enter Box")
            info_msg.setIcon(QMessageBox.Information)

            x = info_msg.exec_()


    def edite_Book(self):
        my_connection=mysql.connector.connect(
            host="localhost",
            user="you'r username",
            password="you'r passwor mysql",
            database="you'r database name"
        )

        my_cursor=my_connection.cursor()

        check=""

        if self.check_Edite_Iranian.isChecked():
            check="Iranian"
        elif self.check_Edite_Foriegn.isChecked():
            check="Foriegn"


        my_cursor.execute("""UPDATE book SET Name=%s,Author=%s,releasData=%s,Description=%s,my_Group=%s WHERE Name=%s
        """,(self.enter_Edite_Name.text(),
        self.enter_Edite_Author.text(),
        int(self.enter_Edite_Releas_Data.text()),
        self.enter_Edite_Description.text(),
        check,
        self.enter_Name_for_search.text()
        ))

        my_connection.commit()

    

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Book_List.setTitle(_translate("Dialog", "Book"))
        item = self.myTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Name Book"))
        item = self.myTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Author Book"))
        item = self.myTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Releas Data"))
        item = self.myTable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Description"))
        item = self.myTable.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Group"))
        self.btn_show_data.setText(_translate("Dialog", "show Data"))
        self.groupBox_2.setTitle(_translate("Dialog", "Delete"))
        self.label_2.setText(_translate("Dialog", "Name :"))
        self.btn_Delete.setText(_translate("Dialog", "Delete"))
        self.myTab.setTabText(self.myTab.indexOf(self.tab_3), _translate("Dialog", "Home"))
        self.lb_Add_Name.setText(_translate("Dialog", "Enter Name Book : "))
        self.lbl_Add_Author.setText(_translate("Dialog", "Enter Author Book : "))
        self.lbl_Add_Releas_Data.setText(_translate("Dialog", "Enter Releas Data : "))
        self.lbl_group.setText(_translate("Dialog", "Group : "))
        self.lbl_Description.setText(_translate("Dialog", "Enter Description : "))
        self.check_Iranian.setText(_translate("Dialog", "Iranian"))
        self.check_Foriegn.setText(_translate("Dialog", "Foriegn"))
        self.label_7.setText(_translate("Dialog", "    Add you\'r Information Book"))
        self.btn_Add_Book.setText(_translate("Dialog", "Add Book"))
        self.myTab.setTabText(self.myTab.indexOf(self.tab), _translate("Dialog", "Add"))
        self.label_8.setText(_translate("Dialog", "       Edite Information Book"))
        self.lbl_Add_Author_2.setText(_translate("Dialog", "Enter Author Book : "))
        self.lbl_Description_2.setText(_translate("Dialog", "Enter Description : "))
        self.check_Edite_Foriegn.setText(_translate("Dialog", "Foriegn"))
        self.lb_Add_Name_2.setText(_translate("Dialog", "Enter Name Book : "))
        self.check_Edite_Iranian.setText(_translate("Dialog", "Iranian"))
        self.lbl_Add_Releas_Data_2.setText(_translate("Dialog", "Enter Releas Data : "))
        self.lbl_group_2.setText(_translate("Dialog", "Group : "))
        self.btn_Edite_Book.setText(_translate("Dialog", "Edite Book"))
        self.lbl_Name_for_Edite.setText(_translate("Dialog", "Enter Name Book for Edite : "))
        self.btn_Edite_Search.setText(_translate("Dialog", "Search Book"))
        self.myTab.setTabText(self.myTab.indexOf(self.tab_2), _translate("Dialog", "Edite "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
